apiVersion: batch/v1
kind: Job
metadata:
  name: checkmarx-dast-scan
spec:
  template:
    spec:
      containers:
      - name: dast-scan
        image: checkmarx/dast:latest
        env:
        - name: CX_APIKEY
          valueFrom:
            secretKeyRef:
              name: cxone-api-key-secret  # This should be the name of the Kubernetes secret storing your API key
              key: apikey  # The key within the secret where the API key is stored
        volumeMounts:
        - name: dast-home
          mountPath: "/dast_home"
        args:
        - "web"
        - "--environment-id=755a1192-47a8-4033-89e1-a81bf2dfd942"
        - "--config=/dast_home/zap_config.yaml"
        - "--base-url=https://sng.ast.checkmarx.net/"
        - "--output=/dast_home/test_output"
        - "--timeout=10000"
        - "--update-interval=10"
        - "--jvm-properties=-Xmx3G"
        - "--log-level=info"
        - "--verbose"
        - "--retry=3"
        - "--retry-delay=20"
      restartPolicy: Never
      volumes:
      - name: dast-home
        hostPath:
          path: "/Users/aaron/Checkmarx/demos/dast/argocd"
          type: Directory
  backoffLimit: 4
